//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfflineARM.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GuiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfflineARM.Gui.GuiResource", typeof(GuiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string AboutBoxProgram_Caption {
            get {
                return ResourceManager.GetString("AboutBoxProgram_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение для элемента с ключом &quot;{0}&quot; в холдере {1} не может быть заменено.
        /// </summary>
        internal static string HolderCannotReplaceValueFormat {
            get {
                return ResourceManager.GetString("HolderCannotReplaceValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap knowledgebasearticle_32x32 {
            get {
                object obj = ResourceManager.GetObject("knowledgebasearticle_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        internal static string LoginForm_Caption {
            get {
                return ResourceManager.GetString("LoginForm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оффлайн клиент.
        /// </summary>
        internal static string MainForm_Caption {
            get {
                return ResourceManager.GetString("MainForm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание заказа.
        /// </summary>
        internal static string OrderForm_CaptionCreateOrder {
            get {
                return ResourceManager.GetString("OrderForm_CaptionCreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент.
        /// </summary>
        internal static string OrderListControl_GridOrderCaption_Customer {
            get {
                return ResourceManager.GetString("OrderListControl_GridOrderCaption_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        internal static string OrderListControl_GridOrderCaption_DateCreate {
            get {
                return ResourceManager.GetString("OrderListControl_GridOrderCaption_DateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес доставки.
        /// </summary>
        internal static string OrderListControl_GridOrderCaption_Delivary {
            get {
                return ResourceManager.GetString("OrderListControl_GridOrderCaption_Delivary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата доставки.
        /// </summary>
        internal static string OrderListControl_GridOrderCaption_DelivaryDate {
            get {
                return ResourceManager.GetString("OrderListControl_GridOrderCaption_DelivaryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string OrderListControl_GridOrderCaption_Number {
            get {
                return ResourceManager.GetString("OrderListControl_GridOrderCaption_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответственный.
        /// </summary>
        internal static string OrderListControl_GridOrderCaption_User {
            get {
                return ResourceManager.GetString("OrderListControl_GridOrderCaption_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        internal static string OrderPayControl_CardPaymentType {
            get {
                return ResourceManager.GetString("OrderPayControl_CardPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличными.
        /// </summary>
        internal static string OrderPayControl_CashPaymentType {
            get {
                return ResourceManager.GetString("OrderPayControl_CashPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кредит.
        /// </summary>
        internal static string OrderPayControl_CreditPaymentType {
            get {
                return ResourceManager.GetString("OrderPayControl_CreditPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string OrderPayControl_GridPayCaption_Date {
            get {
                return ResourceManager.GetString("OrderPayControl_GridPayCaption_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить из оплат.
        /// </summary>
        internal static string OrderPayControl_GridPayCaption_DeleteFromPays {
            get {
                return ResourceManager.GetString("OrderPayControl_GridPayCaption_DeleteFromPays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вручную.
        /// </summary>
        internal static string OrderPayControl_GridPayCaption_IsManual {
            get {
                return ResourceManager.GetString("OrderPayControl_GridPayCaption_IsManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип оплаты.
        /// </summary>
        internal static string OrderPayControl_GridPayCaption_PayType {
            get {
                return ResourceManager.GetString("OrderPayControl_GridPayCaption_PayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string OrderPayControl_GridPayCaption_Summ {
            get {
                return ResourceManager.GetString("OrderPayControl_GridPayCaption_Summ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспозиция.
        /// </summary>
        internal static string OrderSpecificControl_ExpositionCharacteristics {
            get {
                return ResourceManager.GetString("OrderSpecificControl_ExpositionCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string OrderSpecificControl_GridExpositionCaption_Count {
            get {
                return ResourceManager.GetString("OrderSpecificControl_GridExpositionCaption_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в заказ.
        /// </summary>
        internal static string OrderSpecificControl_GridExpositionCaption_Count_AddInOrder {
            get {
                return ResourceManager.GetString("OrderSpecificControl_GridExpositionCaption_Count_AddInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно.
        /// </summary>
        internal static string OrderSpecificControl_GridExpositionCaption_IsEnabled {
            get {
                return ResourceManager.GetString("OrderSpecificControl_GridExpositionCaption_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string OrderSpecificControl_GridExpositionCaption_Name {
            get {
                return ResourceManager.GetString("OrderSpecificControl_GridExpositionCaption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура.
        /// </summary>
        internal static string OrderSpecificControl_GridExpositionCaption_Nomeclature {
            get {
                return ResourceManager.GetString("OrderSpecificControl_GridExpositionCaption_Nomeclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string OrderSpecificControl_GridExpositionCaption_Price {
            get {
                return ResourceManager.GetString("OrderSpecificControl_GridExpositionCaption_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в заказ.
        /// </summary>
        internal static string OrderSpecificControl_GridNomenclatureFeatureCaption_AddInOrder {
            get {
                return ResourceManager.GetString("OrderSpecificControl_GridNomenclatureFeatureCaption_AddInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string OrderSpecificControl_GridNomenclatureFeatureCaption_Name {
            get {
                return ResourceManager.GetString("OrderSpecificControl_GridNomenclatureFeatureCaption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string OrderSpecificControl_GridNomenclatureFeatureCaption_Price {
            get {
                return ResourceManager.GetString("OrderSpecificControl_GridNomenclatureFeatureCaption_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристика.
        /// </summary>
        internal static string OrderSpecificControl_OrderSpecifications_Characteristic {
            get {
                return ResourceManager.GetString("OrderSpecificControl_OrderSpecifications_Characteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string OrderSpecificControl_OrderSpecifications_Count {
            get {
                return ResourceManager.GetString("OrderSpecificControl_OrderSpecifications_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить из заказа.
        /// </summary>
        internal static string OrderSpecificControl_OrderSpecifications_DeleteFromOrder {
            get {
                return ResourceManager.GetString("OrderSpecificControl_OrderSpecifications_DeleteFromOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        internal static string OrderSpecificControl_OrderSpecifications_DiscountProcent {
            get {
                return ResourceManager.GetString("OrderSpecificControl_OrderSpecifications_DiscountProcent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма скидки.
        /// </summary>
        internal static string OrderSpecificControl_OrderSpecifications_DiscountSum {
            get {
                return ResourceManager.GetString("OrderSpecificControl_OrderSpecifications_DiscountSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура.
        /// </summary>
        internal static string OrderSpecificControl_OrderSpecifications_Nomenclature {
            get {
                return ResourceManager.GetString("OrderSpecificControl_OrderSpecifications_Nomenclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string OrderSpecificControl_OrderSpecifications_Price {
            get {
                return ResourceManager.GetString("OrderSpecificControl_OrderSpecifications_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string OrderSpecificControl_OrderSpecifications_TotalSum {
            get {
                return ResourceManager.GetString("OrderSpecificControl_OrderSpecifications_TotalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        internal static string OrderSpecificControl_spNext {
            get {
                return ResourceManager.GetString("OrderSpecificControl_spNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристики.
        /// </summary>
        internal static string OrderSpecificControl_tpOrderCharacteristics {
            get {
                return ResourceManager.GetString("OrderSpecificControl_tpOrderCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string OrderSpecificControl_TreeNomenclatureCaption_Name {
            get {
                return ResourceManager.GetString("OrderSpecificControl_TreeNomenclatureCaption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print_32x32 {
            get {
                object obj = ResourceManager.GetObject("print_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
